### ISSUE TITLE
Why encourage environment variables

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/taxize-book#3]
> We encourage users to use environment variables rather than R options because they are more standard across programming languages and computing environments

What do you mean? That it's a good habit to have because one can use the same habit when learning other languages?

**Comment by sckott** [comment]
- b/c env vars are universally used across servers and user own computer
- b/c env vars used across programming langs, whereas r options are specific to R

**Comment by maelle** [comment]
Thanks for the clarification. "used across programming langs" means that it's a good habit to have, not that the .Renviron would be used by other programming languages, right?

**Comment by sckott** [comment]
.Renviron is specific to R, but you don't have to put env vars in .Renviron to be poicked up in R. can be in .bash_profile, or similar files

**Comment by maelle** [comment]
aaah now I understand the original sentence.

**Comment by maelle** [comment]
should it be rephrased for other 🐨 s?

"If you use only R, we recommend you use .Renviron over .Rprofile. If you use other programming languages as well to access the API, we recommend you use other types of environment variables such as .bash_profile" or something like that?

**Comment by sckott** [comment]
or maybe the first part could be:

> we recommend using environment variables over options in general. 

and then the rest about if you use other languages or not

**Comment by maelle** [comment]
yes sounds good
